### ISSUE TITLE
replace inverse-multiply with solve

### ISSUE THREAD

**Issue by bob-carpenter** [zhouyifan233/ControlVariates#1]
https://github.com/zhouyifan233/ControlVariates/blob/main/controlvariates/controlvariates_basics.py has these two lines:

```python
inv_Sigma_cc = sp.linalg.inv(Sigma_cc)
zv = (-inv_Sigma_cc @ Sigma_cs).T @ control.T
```

This is much more arithmetically stable done with a `solve` operation rather than an inverse-multiply.  See, e.g.,

https://stackoverflow.com/questions/31256252/why-does-numpy-linalg-solve-offer-more-precise-matrix-inversions-than-numpy-li

**Comment by zhouyifan233** [comment]
Hi Bob,
Thank you so much for checking my code. I've altered the code using the function you mentioned.
Cheers,
Yifan
PS. I'll support the bridgestan 1.0.0 soon.

**Comment by bob-carpenter** [comment]
You're welcome, and I'm glad it was helpful.  And thanks for extending to this official release of BridgeStan.
